### ISSUE TITLE
 Multiple dex files 

### ISSUE THREAD

**Issue by tyduztck** [cigalecigales/cordova-plugin-apkInstaller#1]
After installing cordova-plugin-apkinstaller, im getting this error:
com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

I use cordova CLI , command cordova build android to build the apk file. 

Please help me

**Comment by cigalecigales** [comment]
This plugin add android-support-v4 library to your app.
Probably, your app already include this library before installing this plugin.
You need to resolve the library conflict.

**Comment by tyduztck** [comment]
Yup... I have solved the problem, i removed to library provided by this plugin and it works. Thank you so much.
