### ISSUE TITLE
There was a problem parsing the package

### ISSUE THREAD

**Issue by tyduztck** [cigalecigales/cordova-plugin-apkInstaller#2]
I cant retrieve the package location, what i'm missing? Please help. 
I need to specify the <file_path> location?

**Comment by cigalecigales** [comment]
this error?
![parsing error](https://raw.githubusercontent.com/wiki/cigalecigales/cordova-plugin-apkInstaller/images/image05.png)

**Comment by tyduztck** [comment]
yup.. this error, exactly the same issue. please help.

**Comment by tyduztck** [comment]
It works now!! I not sure why but i think is the apk in my app corrupted. Thank you very much!
