### ISSUE TITLE
Installer doesn't launch in my app

### ISSUE THREAD

**Issue by thermostat42** [cigalecigales/cordova-plugin-apkInstaller#3]
Hello,
I would like to use your plugin in my app. I tried your sample and it works (with my distant app).
But : when I try to install and run it in my app, the APK "installer" doesn't want to launch. Otherwise, the configuration is OK and I have all the plugins ready. The APK is downloaded, and "apkInstaller.install(fileName, function(msg) {" returns "OK", but nothing after... Or, more precisely, it seems that something is launched but immediately closed...
I debug it with Chrome console, but no error... And the URI is, in the two cases (in your app and in mine) : _content://[PACKAGE NAME]/apkDirectory/myAPK.apk_. I made all the permissions and the config is the same...
I tried all the possible things, but I didn't make it works...
Please, can you help me ?
For information, I use Nuxt.js (vueJS framework), encapsulated in Cordova.
Thank you,
Best regards,

**Comment by cigalecigales** [comment]
I tried this plugin for the first time in 2 years.
It didn't work, so I updated this.  
   my environment >> cordova v9.0.0  and  android v8.1.0
   my sample source code  >> https://github.com/cigalecigales/ApkInstallerPluginSample2

Please update plugin and try it agein😆

Best regards.

**Comment by thermostat42** [comment]
Hello,
I spent severals hours without being able to make it work, I never thought you could update it 2 years later...
But finally you did and now it **WORKS** !
Thank you very much man, you are great !!!!
Best regards,
